 // add FEEDBACK

export const ADDFEEDBACK_REQUEST="ADDFEEDBACK_REQUEST"
export const ADDFEEDBACK_SUCCESS="ADDFEEDBACK_SUCCESS"
export const ADDFEEDBACK_FAIL="ADDFEEDBACK_FAIL"



// get FEEDBACK

export const GETFEEDBACK_REQUEST="GETFEEDBACK_REQUEST"
export const GETFEEDBACK_SUCCESS="GETFEEDBACK_SUCCESS"
export const GETFEEDBACK_FAIL="GETFEEDBACK_FAIL"



//update  FEEDBACK

export const UPDATEFEEDBACK_REQUEST="UPDATEFEEDBACK_REQUEST"
export const UPDATEFEEDBACK_SUCCESS="UPDATEFEEDBACK_SUCCESS"
export const UPDATEFEEDBACK_FAIL="UPDATEFEEDBACK_FAIL"




// delete FEEDBACK

export const DELETEFEEDBACK_REQUEST="DELETEFEEDBACK_REQUEST"
export const DELETEFEEDBACK_SUCCESS="DELETEFEEDBACK_SUCCESS"
export const DELETEFEEDBACK_FAIL="DELETEFEEDBACK_FAIL"



