//update student

export const UPDATESTUDENT_REQUEST="UPDATESTUDENT_REQUEST"
export const UPDATESTUDENT_SUCCESS="UPDATESTUDENT_SUCCESS"
export const UPDATESTUDENT_FAIL="UPDATESTUDENT_FAIL"


// get student

export const GETSTUDENT_REQUEST="GETSTUDENT_REQUEST"
export const GETSTUDENT_SUCCESS="GETSTUDENT_SUCCESS"
export const GETSTUDENT_FAIL="GETSTUDENT_FAIL"


// delete student

export const DELETESTUDENT_REQUEST="DELETESTUDENT_REQUEST"
export const DELETESTUDENT_SUCCESS="DELETESTUDENT_SUCCESS"
export const DELETESTUDENT_FAIL="DELETESTUDENT_FAIL"