//login for both
export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const LOUGOUT="LOUGOUT"



// siignup student
export const SIGNUP_REQUEST="SIGNUP_REQUEST"
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS"
export const SIGNUP_FAIL="SIGNUP_FAIL"


// signup instractor
export const SIGNUPINSTRACTOR_REQUEST="SIGNUPINSTRACTOR_REQUEST"
export const SIGNUPINSTRACTOR_SUCCESS="SIGNUPINSTRACTOR_SUCCESS"
export const SIGNUPINSTRACTOR_FAIL="SIGNUPINSTRACTOR_FAIL"


//update instractor

export const UPDATEINSTRACTOR_REQUEST="UPDATEINSTRACTOR_REQUEST"
export const UPDATEINSTRACTOR_SUCCESS="UPDATEINSTRACTOR_SUCCESS"
export const UPDATEINSTRACTOR_FAIL="UPDATEINSTRACTOR_FAIL"

// get instractor

export const GETINSTRACTOR_REQUEST="GETINSTRACTOR_REQUEST"
export const GETINSTRACTOR_SUCCESS="GETINSTRACTOR_SUCCESS"
export const GETINSTRACTOR_FAIL="GETINSTRACTOR_FAIL"

// delete instractor 

export const DELETEINSTRACTOR_REQUEST="DELETEINSTRACTOR_REQUEST"
export const DELETEINSTRACTOR_SUCCESS="DELETEINSTRACTOR_SUCCESS"
export const DELETEINSTRACTOR_FAIL="DELETEINSTRACTOR_FAIL"


// get all instractor

export const GETALLINSTRACTOR_REQUEST="GETALLINSTRACTOR_REQUEST"
export const GETALLINSTRACTOR_SUCCESS="GETALLINSTRACTOR_SUCCESS"
export const GETALLINSTRACTOR_FAIL="GETALLINSTRACTOR_FAIL"
